import os

Import('env lib lib_name libsuffix libgtest')

# get a list of source files
unittest_src = set()

CPPPATH = ['#include']
CPPPATH.append(env['GTEST_INCLUDE'])
  
LIBPATH = ['#/lib']
LIBPATH.append('#/third-party/lib')

prev_LIBS = env['LIBS']
LIBS = []
LIBS.extend(prev_LIBS)
LIBS.extend([lib_name,
             'gtest' + libsuffix,
             'gtest_main' + libsuffix,
             'gflags' + libsuffix])

for f in env.Glob('*.cc'):
  path, file = os.path.split(str(f) )
  name, ext = os.path.splitext(file)
   
  unittest = env.Program(file,
              CPPPATH=CPPPATH,
						  LIBPATH=LIBPATH,
              LIBS=LIBS)
  unittest_name = '%s%s%s' % (name, libsuffix, env['PROGSUFFIX'])
  
  depends = [lib]
  
  if libgtest:
    depends.append(libgtest)
    
  env.Depends(unittest, depends)
  env.InstallAs('#/bin/test/%s' % (unittest_name), unittest)