import checks
import os

Import('*')

env.AppendUnique(CPPPATH = ['#include'] )

# get a list of source files
fssw_srcs = set()

for f in env.Glob('*.cc'):
	path, file = os.path.split(str(f) )
	fssw_srcs.add(file)

# compile them into object files
fssw_objs = env.Object(list(fssw_srcs) )

libfssw_name = 'fssw%s' % (libsuffix)
fssw_lib = env.StaticLibrary('#/lib/%s' % (libfssw_name), [fssw_objs] )
env.Alias('lib' + libfssw_name, fssw_lib)

Export('libfssw_name', 'fssw_lib')